name: agriconnect
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0

  # ---- APP UI & STATE PACKAGES ----
  flutter_riverpod: ^3.3.1
  google_fonts: ^6.2.1
  share_plus: 12.0.2
  shared_preferences: ^2.2.2
  app_links: ^3.5.0
  
  # ---- CHAT & NATIVE FUNCTIONALITIES PACKAGES ----
  url_launcher: ^6.2.5
  permission_handler: ^11.3.0
  image_picker: ^1.0.7
  file_picker: ^11.0.2
  geolocator: ^11.0.0
  flutter_contacts: ^1.1.9
  record: ^6.2.0
  path_provider: ^2.1.2
  supabase_flutter: ^2.10.2
  dio: ^5.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # Ye line dotenv file aur images ko app mein read karne ke liye lazmi hai
  assets:
    - .env
    - assets/images/logo.png
    - assets/images/adlytix_logo.png
